# Generated by Django 3.0 on 2019-12-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('type', models.CharField(choices=[('percent', '%'), ('absolute', '$')], max_length=20, verbose_name='Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
            ],
            options={
                'ordering': ('start', '-modified'),
            },
        ),
    ]
