# Generated by Django 3.0 on 2019-12-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ('slug', '-created', '-modified'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ('slug', '-created', '-modified'),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('img', models.ImageField(blank=True, upload_to='portfolio/templates/portfolio/img/', verbose_name='Image')),
                ('desc', models.TextField(verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('categories', models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.Category', verbose_name='Categories')),
                ('tags', models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.Tag', verbose_name='Tags')),
            ],
        ),
    ]
